project:
  type: website
  output-dir: docs # set the output directory to docs to publish on github

website:
  title: "Heyuan Liu" # change the tile to my name
  navbar: # define the top navigation bar
    left: # items placed on the left side of the navigation bar
      - href: index.qmd
        text: Home
      - href: hobbies.qmd # add a link to the new page
        text: Hobbies

format:
  html:
    theme: vapor # use a specific "vapor" theme
    css: styles.css
    toc: true # enable directory function